services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      RABBITMQ_URL: "amqp://guest:guest@mq:5672"
      DATABASE_URL: "postgres://postgres@db:5432/postgres"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
      AUTH_ISSUER_URL: "https://login.microsoftonline.com/YourTenantIdHere/v2.0"
      AUTH_CLIENT_ID: "YourClientIdHere"
      AUTH_CLIENT_SECRET: "YourSecretHere"
      AUTH_SCOPE: "openid profile email XboxLive.signin"
      AUTH_SESSION_SECRET: "YourSecretHere"
    depends_on:
      - mq
      - db

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    environment:
      RABBITMQ_URL: "amqp://guest:guest@mq:5672"
      DATABASE_URL: "postgres://postgres@db:5432/postgres"
    depends_on:
      - mq
      - db

  mq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq:
  postgres:
