services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      RABBITMQ_HOST: rabbitmq
  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
